// # Root Layout (Chứa Font & Providers)

import type { Metadata } from "next";
import { Font } from "../config/fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Lavender Teeducation",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${Font.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}